table Dim_Band
	lineageTag: 2dff9090-925a-4062-b976-397973bf37f5

	column ID_Banda
		dataType: int64
		formatString: 0
		lineageTag: 86b99c43-69a2-4b36-bf8f-83dfd8c036cf
		summarizeBy: none
		sourceColumn: ID_Banda

		annotation SummarizationSetBy = Automatic

	column Bandas
		dataType: string
		lineageTag: 66b937c4-3daa-4607-9ce5-c5a93061659b
		summarizeBy: none
		sourceColumn: Bandas

		annotation SummarizationSetBy = Automatic

	partition Dim_Band = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\USER\OneDrive\Desktop\Proyectos\Power BI\Clases\Clase1\Archivos\Dim_Band.csv"),[Delimiter=";", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ID_Banda", Int64.Type}, {"Bandas", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

